Added CSV & Timetable download capability
FFCSThingy/FFCSThingy2.0 pull request #103
Opened 2020-10-24 13:52 UTC by brij1999

# Details
* **[UPDATED] branched from dev, and verified working.**
* This PR aims to resolve #74 .
* It provides two buttons in the UI component just before the timetable, that allows the users to download the PNG image of timetable, and a CSV record of the selected courses.

# Updated UI
![1](https://user-images.githubusercontent.com/36758947/97050456-0270e780-159b-11eb-93d6-a203be44faf4.png)

# CSV file
![Screenshot from 2020-10-24 01-39-37](https://user-images.githubusercontent.com/36758947/97050553-33e9b300-159b-11eb-9434-13ee4c04f691.png)

# Screenshots Captured
* Desktop version:
![FFCSThingy - Timetable](https://user-images.githubusercontent.com/36758947/97050494-174d7b00-159b-11eb-9e26-61d8ca36633b.png)

* Mobile version:
![FFCSThingy - Timetable (1)](https://user-images.githubusercontent.com/36758947/97050517-22081000-159b-11eb-981f-1e8fb19555db.png)

2020-10-24 13:53 UTC, brij1999 commented
@namsnath please have a look.

2020-10-24 14:17 UTC, namsnath requested changes
Added a bunch of comments, please try to update accordingly.
Adding the `ESLint` extension or running `npm lint` should help find formatting and syntax issues.

There are a few ESLint errors that will show up in other files, can ignore those, I'll be working on those.

2020-10-24 14:17 UTC, namsnath commented on client/src/components/TimetableSwitcher/TimetableSwitcher.tsx
> +        (state: RootState) => selectFilteredTimetable(state),
This is an anti-pattern. The `selectFilteredTimetable` is a selector in itself
```suggestion
        const timetable = useSelector(selectFilteredTimetable);
```

2020-10-24 14:17 UTC, namsnath commented on client/src/components/TimetableSwitcher/TimetableSwitcher.tsx
> +import selectFilteredTimetable from '../../selectors/timetable';
The export for this was updated recently. You might have to do `{ selectFilteredTimetable }`. Please check.
```suggestion
import { selectFilteredTimetable } from '../../selectors/timetable';
```

2020-10-24 14:17 UTC, namsnath commented on client/src/components/TimetableSwitcher/TimetableSwitcher.tsx
> +        csv += header + '\n' + values;
Try to use `const` here instead.
```suggestion
        const header = Object.keys(timetable[0]).filter((val, index) => index!==0).join(',');
        const values = timetable.map(o => Object.values(o).filter((val, index) => index!==0).join(',')).join('\n');
        const csv = `${header}\n${values}`;
```

2020-10-24 14:17 UTC, namsnath commented on client/src/components/TimetableSwitcher/TimetableSwitcher.tsx
> +        console.log(csv);
Remove the `console.log()`

2020-10-24 14:17 UTC, namsnath commented on client/src/components/TimetableSwitcher/TimetableSwitcher.tsx
> +        let header = Object.keys(timetable[0]).filter((val, index) => index!==0).join(',');
This might fail if `timetable` is `[]`. Add nullish checks please.
Also run `npm lint` or add `ESLint` as an extension to your editor. 
```suggestion
        let header = Object.keys(timetable[0]).filter((val, index) => index !== 0).join(',');
```

2020-10-24 14:17 UTC, namsnath commented on client/src/components/TimetableSwitcher/TimetableSwitcher.tsx
> +        triggerBase64Download(imgData, 'FFCSThingy - Timetable');
Change the name to reflect active timetable please.
```suggestion
        triggerBase64Download(imgData, `FFCSThingy - ${activeTimetableName}`);
```

2020-10-24 14:17 UTC, namsnath commented on client/src/components/TimetableSwitcher/TimetableSwitcher.tsx
>  	const activeTimetableName = useSelector(
This wasn't in your changes, but could use an update to use the exported selector from `selectors/timetable.ts`
```suggestion
	const activeTimetableName = useSelector(selectActiveTimetableName);
```

2020-10-24 14:17 UTC, namsnath commented on client/src/components/TimetableSwitcher/TimetableSwitcher.tsx
> +import domtoimage from 'dom-to-image';
Could be renamed to `domToImage` to stick to naming conventions.
```suggestion
import domToImage from 'dom-to-image';
```

2020-10-24 14:17 UTC, namsnath commented on client/src/components/TimetableSwitcher/TimetableSwitcher.tsx
> +        downloadLink.download = "FFCSThingy - courses.csv";
Similar to above, name could be changed to include active timetable name.

2020-10-24 14:17 UTC, namsnath commented on client/src/components/TimetableSwitcher/TimetableSwitcher.tsx
> +                    <FaDownload />
Could this be changed to `FaCamera` instead? Looks more intuitive if it saves a picture of the timetable.

2020-10-24 14:17 UTC, namsnath commented on client/src/components/TimetableSwitcher/TimetableSwitcher.tsx
> +    const handleSaveTimetable = async () => {
Rename to something like `handleTimetableScreenshot`? Sounds more intuitive.

2020-10-24 14:17 UTC, namsnath commented on client/src/components/TimetableSwitcher/TimetableSwitcher.tsx
> +    const handleSaveCourses = async () => {
Similar to above, rename to something more intuitive? `handleSaveCourseCsv` is a possible option.

2020-10-24 14:17 UTC, namsnath commented on client/src/components/TimetableSwitcher/TimetableSwitcher.tsx
> +                    <FaFileDownload />
There seems to be some formatting issue. Run ESLint and fix please.

2020-10-24 14:17 UTC, namsnath commented on client/src/css/Timetable.module.scss
> +    padding-bottom: 2rem;
Indentation. Files use tabs: 4. Try to stick to that please.

2020-10-24 14:17 UTC, namsnath commented on client/src/types/react-base64-downloader.d.ts
> +declare module "react-base64-downloader";
Why is this file needed?

2020-10-24 14:19 UTC, namsnath commented
@brij1999 , could you please commit your `package.json` and `package-lock.json` as well if you've added dependencies?

2020-10-24 14:26 UTC, namsnath requested changes

2020-10-24 14:26 UTC, namsnath commented on client/src/components/TimetableSwitcher/TimetableSwitcher.tsx
> +        let values = timetable.map(o => Object.values(o).filter((val, index) => index!==0).join(',')).join('\n');
This iteration might fail or introduce buggy data. Try saving the order of keys in `header` and reuse the order in this statement.

2020-10-24 18:41 UTC, namsnath commented
You don't seem to have fixed formatting issues. Try running a `npm lint`

Also, your local dev branch isn't up to date with the repo dev. You can try a PR from repo dev to your fork's dev to get it up to date. The changes you made to selectors/timetable are already there.

2020-10-24 18:58 UTC, brij1999 commented
Bro please share the linting errors that you are getting. I have run it multiple times, and it shows no errors : (
![Screenshot from 2020-10-25 00-27-24](https://user-images.githubusercontent.com/36758947/97091340-f5b2c900-1658-11eb-834f-5d7ec7731135.png)

2020-10-24 19:00 UTC, namsnath commented
What's the isEmpty util? Looks like overkill to me. Could just check empty arrays with something like the `??` (nullish coalescing operator) or the `.?` (optional chaining operator)

2020-10-24 19:02 UTC, brij1999 commented
It could be potentially useful for other use-cases too. That's why I separated it. I wrote a very general validator, that can handle empty cases from a lot of scenarios: arrays, objects, undefined, null, you get the idea.

If you think its overkill I can remove it.

2020-10-24 19:02 UTC, namsnath commented
@brij1999 I'll check it out in an editor tomorrow. Was checking on GitHub. 

Could you fix the other stuff till then?

2020-10-24 19:04 UTC, brij1999 commented
It should be fixed now... I mean the changes suggested at the very start.
Or is there something else apart from those?

2020-10-24 19:05 UTC, brij1999 commented
I have updated the branch too, with latest FFCS:/dev

2020-10-24 19:07 UTC, namsnath commented
The isEmpty is definitely overkill. Just need an inline check. I mentioned the operators above, or something as simple as a ternary check. 

There was also a comment about the values and headers variables which might be buggy. Have a look at that. 

I'll have a proper look in the morning and get back with any other changes.

2020-10-25 02:41 UTC, namsnath commented
@brij1999 Looks good to me for now, merging it.
Have a few minor changes in mind, will refer to them in the original issue if you want to have a look.

2020-10-25 02:42 UTC, merged